import * as Yup from 'yup';

export const validationSchema = Yup.object().shape({
    appDate: Yup.string().required('Application date is required'),
    applicantName: Yup.object().shape({
      firstName: Yup.string().required('First name is required'),
      middleName: Yup.string(),
      lastName: Yup.string().required('Last name is required'),
    }),
    gender: Yup.string().required('Gender is required'),
    age: Yup.number().required('Age is required'),
    address: Yup.object().shape({
      street: Yup.string().required('Street is required'),
      city: Yup.string().required('City is required'),
      zip: Yup.string().required('Zip code is required'),
    }),
    phone: Yup.string().required('Phone number is required'),
    otherLastName: Yup.object().shape({
      otherLastName2: Yup.string(),
      otherLastName3: Yup.string(),
      otherLastName4: Yup.string(),
    }),
    homeless: Yup.string(),
    disabled: Yup.string(),
    helpRequest: Yup.object().shape({
      rent: Yup.string(),
      gasoline: Yup.string(),
      licensePlate: Yup.string(),
      busTicket: Yup.string(),
      food: Yup.string(),
    }),
    IdSource: Yup.object().shape({
      license: Yup.string(),
      expDate: Yup.string(),
      ssn: Yup.string(),
    }),
    singleMale: Yup.string(),
    singleFemale: Yup.string(),
    children: Yup.object().shape({
      isChildren: Yup.string(),
      boyNumber: Yup.string(),
      boyAge: Yup.string(),
      girlNumber: Yup.string(),
      girlAge: Yup.string(),
      childrenRel: Yup.string(),
      schoolDistrict: Yup.string(),
      schoolName: Yup.string(),
    }),
    adults: Yup.object().shape({
      isAdults: Yup.string(),
      numberOfAdults: Yup.string(),
      adultInformation1: Yup.object().shape({
        lastName1: Yup.string(),
        middleName1: Yup.string(),
        firstName1: Yup.string(),
        adultSex1: Yup.string(),
        adultAge1: Yup.string(),
        adultRel1: Yup.string(),
      }),
      adultInformation2: Yup.object().shape({
        lastName2: Yup.string(),
        middleName2: Yup.string(),
        firstName2: Yup.string(),
        adultSex2: Yup.string(),
        adultAge2: Yup.string(),
        adultRel2: Yup.string(),
      }),
      adultInformation3: Yup.object().shape({
        lastName3: Yup.string(),
        middleName3: Yup.string(),
        firstName3: Yup.string(),
        adultSex3: Yup.string(),
        adultAge3: Yup.string(),
        adultRel3: Yup.string(),
      }),
      adultInformation4: Yup.object().shape({
        lastName4: Yup.string(),
        middleName4: Yup.string(),
        firstName4: Yup.string(),
        adultSex4: Yup.string(),
        adultAge4: Yup.string(),
        adultRel4: Yup.string(),
      }),
    }),
    landlord: Yup.object().shape({
      landlordName: Yup.string(),
      interviewerCheck: Yup.string(),
      street: Yup.string(),
      city: Yup.string(),
      zip: Yup.string(),
      phone: Yup.string(),
    }),
    income: Yup.object().shape({
      totalIncome: Yup.string(),
      monthlyIncome: Yup.string(),
      numberMembers: Yup.string(),
    }),
    demographics: Yup.object().shape({
        numAmericanIndian: Yup.number().min(0, 'Number cannot be negative'),
        numAsian: Yup.number().min(0, 'Number cannot be negative'),
        numBlack: Yup.number().min(0, 'Number cannot be negative'),
        numLatinx: Yup.number().min(0, 'Number cannot be negative'),
        numNative: Yup.number().min(0, 'Number cannot be negative'),
        numWhite: Yup.number().min(0, 'Number cannot be negative'),
        numOther: Yup.number().min(0, 'Number cannot be negative'),
        numMulti: Yup.number().min(0, 'Number cannot be negative'),
        numUnknown: Yup.number().min(0, 'Number cannot be negative'),
      }),
    });

   // module.exports = { validationSchema };
   export default validationSchema;